name: Build EXE with Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests flask pillow

    - name: Build EXE
      run: |
        # templates 에러를 해결하기 위해 해당 경로 제외
        pyinstaller --onefile --add-data "ghost_image.png;." main.py
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_project_exe
        path: dist/main.exe
